# Generated by Django 5.1.15 on 2026-05-12 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_petty_cash_and_vat_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('inflow_from_main_cash', 'Inflow from Main Cash'), ('inflow_other', 'Inflow from Other Source'), ('expense', 'Expense'), ('return_to_main_cash', 'Return to Main Cash')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expense_category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('receipt_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_expenses', to='core.account')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
