# Generated by Django 5.1.15 on 2026-05-12 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vat_and_cogs_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='core_journa_date_f2e922_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='core_journa_source__834c01_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['is_reconciled'], name='core_journa_is_reco_5d9657_idx'),
        ),
    ]
