"""
Django settings for accounting_system project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# In production: set DJANGO_SECRET_KEY env var to a long random string.
# In development: falls back to the insecure default below.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=h$n^3((i*cu0we#ss##dpo(sr49(gr$=j*ksq-1))v#cus%1+'
)

# In production: set DEBUG=False env var.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,192.168.1.18,.ngrok-free.app,.ngrok.io,.vercel.app'
).split(',')

# Include Vercel's auto-assigned URL
_VERCEL_URL = os.environ.get('VERCEL_URL', '')
if _VERCEL_URL and _VERCEL_URL not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_VERCEL_URL)

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://*.vercel.app',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'core',
    'petrol',
    'cargo',
    'reports',
    'sales',
]

JAZZMIN_SETTINGS = {
    "site_title": "TBC Admin",
    "site_header": "TBC Management System",
    "site_brand": "TBC",
    "site_logo": None,
    "welcome_sign": "Welcome to TBC Back Office",
    "copyright": "TBC Management System",
    "search_model": ["auth.User"],
    "topmenu_links": [
        {"name": "Main App", "url": "/", "new_window": False, "icon": "fas fa-home"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.User": "fas fa-users",
        "auth.Group": "fas fa-users-cog",
        "core.Business": "fas fa-building",
        "core.Account": "fas fa-list",
        "core.JournalEntry": "fas fa-book",
        "core.Employee": "fas fa-id-badge",
        "core.SalaryPayment": "fas fa-money-bill-wave",
        "petrol.FuelType": "fas fa-gas-pump",
        "petrol.Tank": "fas fa-database",
        "petrol.FuelSupplier": "fas fa-truck",
        "petrol.CreditCustomer": "fas fa-user-tag",
        "petrol.DailyFuelSale": "fas fa-receipt",
        "petrol.FuelPurchase": "fas fa-shopping-cart",
        "petrol.CreditSale": "fas fa-credit-card",
        "petrol.CreditPayment": "fas fa-hand-holding-usd",
        "petrol.PetrolExpense": "fas fa-file-invoice-dollar",
        "cargo.Vehicle": "fas fa-truck-moving",
        "cargo.Driver": "fas fa-user-tie",
        "cargo.CargoCustomer": "fas fa-address-book",
        "cargo.Trip": "fas fa-map-marked-alt",
        "cargo.Invoice": "fas fa-file-invoice",
        "cargo.VehicleExpense": "fas fa-tools",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'accounting_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accounting_system.wsgi.application'


# Database — prefer non-pooling URL (avoids pgbouncer issues with advisory locks)
_POSTGRES_URL = (
    os.environ.get('POSTGRES_URL_NON_POOLING')
    or os.environ.get('DATABASE_URL_UNPOOLED')
    or os.environ.get('POSTGRES_URL')
    or os.environ.get('DATABASE_URL')
)
if _POSTGRES_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _POSTGRES_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'public' / 'static'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# HTTPS security — auto-enable in production (DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Auth URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
