# Generated by Django 5.1.15 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0002_seed_fuel_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpurchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('credit', 'Credit (Supplier Account)')], default='cash', max_length=10),
        ),
    ]
