# Generated by Django 5.1.15 on 2026-05-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing(apps, schema_editor):
    FuelPurchase = apps.get_model('petrol', 'FuelPurchase')
    FuelPurchase.objects.all().update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0003_add_payment_method_to_fuelpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpurchase',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fuelpurchase',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelpurchase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.RunPython(approve_existing, migrations.RunPython.noop),
    ]
