# Generated by Django 5.1.15 on 2026-05-12 10:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0004_purchase_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Current selling price per litre (set by management)', max_digits=10),
        ),
    ]
