# Generated by Django 5.1.15 on 2026-05-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0005_tank_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per litre from last approved purchase (auto-updated)', max_digits=10, null=True),
        ),
    ]
