# Generated by Django 5.1.15 on 2026-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0006_tank_last_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpurchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('tigopesa', 'Yas (Tigo Pesa)'), ('halopesa', 'HaloPesa'), ('airtelmoney', 'Airtel Money'), ('credit', 'Credit (Supplier Account)')], default='cash', max_length=20),
        ),
    ]
