# Generated by Django 5.1.15 on 2026-05-12 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0008_migrate_mobile_to_mpesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelpurchase',
            index=models.Index(fields=['status'], name='petrol_fuel_status_a5fcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelpurchase',
            index=models.Index(fields=['date'], name='petrol_fuel_date_e450cb_idx'),
        ),
    ]
