# Generated by Django 5.1.15 on 2026-05-17 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['date'], name='petrol_cred_date_6d18da_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['date'], name='petrol_cred_date_49c853_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyfuelsale',
            index=models.Index(fields=['date'], name='petrol_dail_date_67e80d_idx'),
        ),
        migrations.AddIndex(
            model_name='petrolexpense',
            index=models.Index(fields=['date'], name='petrol_petr_date_3880d3_idx'),
        ),
    ]
