# Generated by Django 5.1.15 on 2026-05-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity_tons',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Load capacity in metric tons', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
