# Generated by Django 5.1.15 on 2026-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_vehicle_capacity_tons_driver_license_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('tigopesa', 'Yas (Tigo Pesa)'), ('halopesa', 'HaloPesa'), ('airtelmoney', 'Airtel Money')], max_length=20),
        ),
    ]
