# Generated by Django 5.1.15 on 2026-05-17 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_migrate_mobile_to_mpesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='cargo_invoi_date_32bf6b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_paid'], name='cargo_invoi_is_paid_f72968_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date'], name='cargo_trip_date_6405b3_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='cargo_trip_status_579f0b_idx'),
        ),
    ]
