# Generated by Django 5.1.15 on 2026-05-12 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('sales', '0003_quotation_quotationline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('cargo_description', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=200)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_signature_received', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.customer')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='cargo.trip')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
